---  
- hosts: all
 
  vars:
   ansible_host_key_checking: false 
 
 
  tasks:
 
  - name: copy war 
    copy: 
     src: /var/lib/jenkins/workspace/Sara-Deploy_on_Container/webapp/target/webapp.war 
     dest: /opt/docker

  - name: Stop current container 
    command: docker stop sara-devops-container 
    ignore_errors: yes
    docker_container: 
      name: sara-devops-container 
      state: stopped

  - name: remove stopped container 
    command: docker rm sara-devops-container 
    ignore_errors: yes 
    docker_container: 
      name: sara-devops-container 
      state: absent

  - name: remover docker images # Clean up task 
    command: docker rmi sara-devops-image:latest 
    ignore_errors: yes # May not find image if first run
    docker_image:  
      name: sara-devops-image:latest 
      state: absent 

  - name: create docker image using war file 
    command: docker build -t sara-devops-image:latest . 
    args: 
     chdir: /opt/docker
    docker_image: 
      name: sara-devops-image:latest . 
      build_path: /opt/docker/sara
      state: present

  - name: run container 
    command: docker run -d --name sara-devops-container -p 8082:8080 sara-devops-image:latest
    docker_container: 
      name: sara-devops-container 
      state: started 
      image: sara-devops-image:latest 
      detach: yes 
      ports: 
      - "8082:8080" 
