---  
- hosts: all
 
  vars:
   ansible_host_key_checking: false 
 
 
  tasks:
 
  - name: copy war 
    copy: 
     src: /var/lib/jenkins/workspace/Sara-Deploy_on_Container/webapp/target/webapp.war 
     dest: /opt/docker

  - name: Stop current container 
    docker_container: 
      name: sara-devops-container 
      state: stopped

  - name: remove stopped container 
    docker_container: 
      name: sara-devops-container 
      state: absent
    
  - name: remover docker images # Clean up task 
    docker_image:  
      name: sara-devops-image:latest 
      state: absent 
 
  - name: create docker image using war file 
    docker_image: 
      name: sara-devops-image:latest . 
      build_path: /opt/docker/sara
      state: present
 
  - name: run container 
    docker_container: 
      name: sara-devops-container 
      state: started 
      image: sara-devops-image:latest 
      detach: yes 
      ports: 
      - "8082:8080" 

    
