---
- hosts: all
  become: true
  vars:
    ansible_sudo_pass: "{{ ansible_ssh_pass }}"
       
  tasks:
  - name: copy Dockerfile 
    copy: 
     src: /var/lib/jenkins/workspace/soufiane_test_3/Dockerfile
     dest: /opt/docker

  - name: copy war 
    copy: 
     src: /var/lib/jenkins/workspace/soufiane_test_3/target/bootcamp.war 
     dest: /opt/docker
      
  - name: Stop current container
    command: docker stop soufiane_test_3
    ignore_errors: yes #why do you think is here?
    
  - name: remove stopped container
    command: docker rm soufiane_test_3
    ignore_errors: yes
    
  - name: remover docker images # Clean up task
    command: docker rmi soufiane_test_3:latest
    ignore_errors: yes # May not find image if first run
    
  - name: create docker image using war file
    command: docker build -t soufiane_test_3 .
    args:
      chdir: /opt/docker
      
  - name: run container
    command: docker run -d --name soufiane_test_3 -p 8082:8080 soufiane_test_3