---
- hosts: 10.4.0.13
  vars:
       ansible_host_key_checking:  false
       become: true
  tasks:
  - name: Stop current container
    command: docker stop sara-devops-container
    ignore_errors: yes
  - name: remove stopped container
    command: docker rm sara-devops-container
    ignore_errors: yes
  - name: remover docker images # Clean up task
    command: docker rmi sara-devops-image:latest
    ignore_errors: yes # May not find image if first run
  - name: create docker image using war file
    command: docker build -t sara-devops-image:latest .
    args:
      chdir: /opt/docker/
  - name: run container
    command: docker run -d --name sara-devops-container -p 8081:8080 sara-devops-image:latest
