---  
- hosts: all
 
  vars:
   ansible_host_key_checking: false 
 
 
  tasks:
 
  - name: copy report 
    fetch:  
     src: /home/ansadmin/report.json
     dest: /var/lib/jenkins/workspace/Sara_Advanced_Deployment_withJFrog
